### ISSUE TITLE
Errors << sensable_phantom_ros:make

### ISSUE THREAD

**Issue by kamilcetin** [jhu-saw/sawSensablePhantom#4]
Is there anybody installed this with ros noetic on ubuntu 20.04? When I do catkin build, I got one error:

Errors     << sensable_phantom_ros:make /home/kamil/touch_ws/logs/sensable_phantom_ros/build.make.001.log
/usr/bin/ld: warning: libncurses.so.5, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libHD.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtinfo.so.5, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libHD.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libHD.so: undefined reference to `stdscr'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libHD.so: undefined reference to `wgetch'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sensable_phantom.dir/build.make:118: /home/kamil/touch_ws/devel/.private/sensable_phantom_ros/lib/sensable_phantom_ros/sensable_phantom] Error 1
make[1]: *** [CMakeFiles/Makefile2:526: CMakeFiles/sensable_phantom.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/kamil/touch_ws/build/sensable_phantom_ros; catkin build --get-env sensable_phantom_ros | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

.............................................................................................
Failed     << sensable_phantom_ros:make                    [ Exited with code 2 ]            
Failed    <<< sensable_phantom_ros                         [ 0.6 seconds ]                   
[build] Summary: 14 of 15 packages succeeded.                                                
[build]   Ignored:   None.                                                                   
[build]   Warnings:  None.                                                                   
[build]   Abandoned: None.                                                                   
[build]   Failed:    1 packages failed.                                                      
[build] Runtime: 2.8 seconds total.

**Comment by adeguet1** [comment]
This might be because the HD libs are compiled against an old libncurse.  Can you try to install them using:
```sh
sudo apt install libncurses5-dev
```
And then try to build again.  Let us know if that fixed the issue.
