### ISSUE TITLE
How to launch FireWire Version of Omni in ROS2

### ISSUE THREAD

**Issue by xiancaiguazi** [jhu-saw/sawSensablePhantom#6]
I have successfully launched the device using the `main` branch for ROS1. 
However, when I tried to launch the device using the `devel` branch for ROS2, it seems the default device is the USB version of Omni and I did not find where to modify the default device.
1. Basic info
OS version: Ubuntu 22.04
ROS2 version: humble
Pakage version: I used `vcs import --recursive --input https://raw.githubusercontent.com/jhu-saw/vcs/main/ros2-sensable-devel.vcs
` to download required packages.
Device driver: [phantom-omni-1394-drivers](https://github.com/jhu-cisst-external/phantom-omni-1394-drivers) is installed.
2. Issue
When I launched the device using `ros2 launch sensable_phantom_models omni_rviz.launch.py`, it had error: 
```
[sensable_phantom-1] $GTDD_HOME not set. Using Default value : /home/lab/.3dsystems
[sensable_phantom-1] : Success
[sensable_phantom-1] stty: /dev/ttyACM300: No such file or directory
[sensable_phantom-1] -E Class mtsSensableHD: SensableHD:arm: 1.73327e+09s, #1: arm: failed to initialize device "arm": error "Communication Error: Check the device connection and configuration."
```
It seems the default device `/dev/ttyACM300` is defined in `/home/lab/.3dsystems`. How can I set the default device as FireWire port?

**Comment by adeguet1** [comment]
two questions:

- did you run the Phantom configuration program and if so, did it find the FireWire device (serial number should be displayed)?

- I could be wrong but I think the FireWire drivers don’t have any reference to GTDD so it looks like you might still have some more recent drivers installed.  As far as I know the two versions of drivers can not cohabitate on a single computer.


On Dec 3, 2024, at 19:20, xiancaiguazi ***@***.***> wrote:



I have successfully launched the device using the main branch for ROS1.
However, when I tried to launch the device using the devel branch for ROS2, it seems the default device is the USB version of Omni and I did not find where to modify the default device.

  1.  Basic info
OS version: Ubuntu 22.04
ROS2 version: humble
Pakage version: I used vcs import --recursive --input https://raw.githubusercontent.com/jhu-saw/vcs/main/ros2-sensable-devel.vcs to download required packages.
Device driver: phantom-omni-1394-drivers<https://github.com/jhu-cisst-external/phantom-omni-1394-drivers> is installed.
  2.  Issue
When I launched the device using ros2 launch sensable_phantom_models omni_rviz.launch.py, it had error:

[sensable_phantom-1] $GTDD_HOME not set. Using Default value : /home/lab/.3dsystems
[sensable_phantom-1] : Success
[sensable_phantom-1] stty: /dev/ttyACM300: No such file or directory
[sensable_phantom-1] -E Class mtsSensableHD: SensableHD:arm: 1.73327e+09s, #1: arm: failed to initialize device "arm": error "Communication Error: Check the device connection and configuration."


It seems the default device /dev/ttyACM300 is defined in /home/lab/.3dsystems. How can I set the default device as FireWire port?

**Comment by xiancaiguazi** [comment]
Thanks for your reply. 
It turns out the system does have some more recent drivers installed. 
The problem is solved by using scripts [uninstall-3ds-openhaptics-3.4.sh](https://github.com/jhu-saw/sawSensablePhantom/blob/main/utils/uninstall-3ds-openhaptics-3.4.sh) to uninstall other drivers.

**Comment by xiancaiguazi** [comment]
Thanks for your reply.
It turns out the system does have some more recent drivers installed.
The problem is solved by using scripts [uninstall-3ds-openhaptics-3.4.sh](https://github.com/jhu-saw/sawSensablePhantom/blob/main/utils/uninstall-3ds-openhaptics-3.4.sh) to uninstall other drivers.
